print("Welcome to the tip calculator.")
totalBill = float(input("What was the total bill? $"))
percentage = int(input("What percentage tip would you like to give? 10, 12 or 15? "))
people = int(input("How many people to split the bill? "))
tip = totalBill + totalBill * (percentage / 100)
print(f"Each person should pay: ${ round(tip / people, 2) }")
